export default {
  LOAD_ROUTINES: 'LOAD_ROUTINES',
  LOAD_ROUTINES_SUCCESS: 'LOAD_ROUTINES_SUCCESS',
  LOAD_EXERCISES: 'LOAD_EXERCISES',
  LOAD_EXERCISES_SUCCESS: 'LOAD_EXERCISES_SUCCESS',
  SAVE_EXERCISE: 'SAVE_EXERCISE',
  SAVE_EXERCISE_SUCCESS: 'SAVE_EXERCISE_SUCCESS',
  SAVE_ROUTINE: 'SAVE_ROUTINE',
  SAVE_ROUTINE_SUCCESS: 'SAVE_ROUTINE_SUCCESS',
  DELETE_EXERCISE: 'DELETE_EXERCISE',
  DELETE_EXERCISE_SUCCESS: 'DELETE_EXERCISE_SUCCESS'
}